server:
    port: 8081

spring:
    profiles:
        active: dev
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/one_to_many
        username: postgres
        password: 123456
        hikari:
              maximum-pool-size: 10
              minimum-idle: 2
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.hazelcast.instance_name: EWMService
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
            hibernate.enable_lazy_load_no_trans: true
            hibernate.jdbc.lob.non_contextual_creation: true
    liquibase:
      contexts: dev
      change-log: classpath:db-changelog.xml

